company_name: Sap
logo_url: 
primary_color: "#007acc"
page_title: "Sap Service Health Dashboard"
header_text: "âš™ Sap Service Monitor"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
